apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfspod
  labels:
    app: nfspod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfspod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfspod
    spec:
      containers:
      - image: nginx:latest
        ports:
        - containerPort: 80
          name: http
        name: nginx
        volumeMounts:
          - name: data
            mountPath: "/usr/share/nginx/html"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs